### ISSUE TITLE
Application Domain corruption when running unit tests

### ISSUE THREAD

**Issue by fabricioferreira** [SlapperAutoMapper/Slapper.AutoMapper#30]
I'm facing an interesting issue while running the unit tests for my application when the code being tested is using Slapper.AutoMapper. As far as I could see, it seems to be related to the use of .Net Remoting for the object caching. The symptom is very strange: the unit test process aborts and no tests are executed. I was only able to get more information on the error when I debugged the .Net assemblies and found that the Application Domain was being corrupted.

First, the exception was that my Pocos were not marked as Serializable. Then, I was only able to solve the issue by implementing **MarshalByRefObject** on my entities classes.

Do you guys ever had this issue before? I'm having this issue with Visual Studio 2015 Update 2, in a .Net Framework 4.6.1 assembly. For now, I'm able to circumvent this issue successfully in my application using the workaround above, but I'm not sure what impact it could have in my application.

**Comment by randyburden** [comment]
I actually ran into this issue years ago as well and from what I recall it was due to the test runner I was using at the time which I believe was JetBrain's ReSharper version 8. There was a known issue in the bug tracker where they admitted that the test runner had issues whenever it accessed the  System.Runtime.Remoting.Messaging.CallContext class. They have since fixed the bug a few years ago as far as I know.

We have plenty of apps and the company I work for that uses Slapper and we've never had an issue so I wouldn't worry about it having an impact in production as the CallContext class is used in many popular .NET projects including ASP.NET itself in order to synchronize WebContext.Current across threads and such.

**Comment by fabricioferreira** [comment]
In my case I'm not using ReSharper, and I'm running these tests using VsTest.Console from within Visual Studio 2015.

It seems the problem because my project doesn't have System.Web referenced, and then the caching mechanism will use remoting instead of the HttpContext to store the values. I'll make some tests later and will provide the feedback.

**Comment by odelvalle** [comment]
Hi @fabricioferreira 

Cache instance in Slapper.Automapper is static and persists when the test ends.

Include Cleanup to avoid this error.
```cs
[TestCleanup] 
public void Cleanup() 
{ 
   Slapper.AutoMapper.Cache.ClearInstanceCache(); 
} 
```
